# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HOR1 = QtWidgets.QPushButton(self.centralwidget)
        self.HOR1.setGeometry(QtCore.QRect(10, 90, 111, 91))
        self.HOR1.setObjectName("HOR1")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(20, 10, 141, 51))
        self.Titulo.setObjectName("Titulo")
        self.HOR2 = QtWidgets.QPushButton(self.centralwidget)
        self.HOR2.setGeometry(QtCore.QRect(130, 90, 111, 91))
        self.HOR2.setObjectName("HOR2")
        self.DB = QtWidgets.QPushButton(self.centralwidget)
        self.DB.setGeometry(QtCore.QRect(250, 90, 111, 91))
        self.DB.setObjectName("DB")
        self.FECHAHORA = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.FECHAHORA.setGeometry(QtCore.QRect(170, 270, 194, 22))
        self.FECHAHORA.setObjectName("FECHAHORA")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 200, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HOR1.setText(_translate("MainWindow", "HOR 1"))
        self.Titulo.setText(_translate("MainWindow", "HORNO DE MADURACION"))
        self.HOR2.setText(_translate("MainWindow", "HOR 2"))
        self.DB.setText(_translate("MainWindow", "BASE DE DATOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
